-- =============================================================================
-- 0040_popularity_indicator_owner_toggle.sql
-- Purpose: Phase 6, sub-feature 4 of "Live Availability, Smart Booking &
-- Real-Time Restaurant Experience" is now fully built AND verified end to
-- end in production with real data: the 🔥 "Popular time" badge on the
-- Live Availability chips (BookingForm.tsx's LiveAvailabilityPanel) --
-- confirmed live on 2026-09-16 test data for Melina restaurant, showing the
-- badge on exactly the 20:00 slot (the one bucket seeded to be
-- historically busiest) and no other slot.
--
-- Getting there took real debugging (see PRs #8-#13 on
-- polarpia-tech/reservex): a production bug where the 6th+ sequential/
-- concurrent Supabase request within one server render returned a wrong
-- answer was masking correct data as a false flag check. Fixed by 0038
-- (batch all flag checks into one round trip) + 0039 (bound/dedupe that
-- batch's input, a security review finding). None of that debugging is
-- specific to popularity_indicator itself -- it would have hit whichever
-- flag happened to land in that position -- so this migration is the
-- originally-planned, unrelated final step: same "follow-up migration"
-- pattern as 0033 (waitlist_public) and 0035 (last_minute_alerts).
--
-- No app code changes needed anywhere: page.tsx already resolves
-- 'popularity_indicator' per restaurant via the batched flag fetch, and the
-- mobile owner settings screen (live-features.tsx) already renders one row
-- per is_owner_configurable flag it finds in the database -- flipping this
-- one column is the entire schema change. The corresponding
-- settings.liveFeaturesFlags.popularity_indicator (and .last_minute_alerts,
-- an existing gap from 0035 noticed while doing this one) label/description
-- i18n keys are added in this same change across all 4 locales so that
-- screen doesn't show a missing-translation key the moment an owner opens
-- it.
--
-- 'live_occupancy' (the one remaining Live-Availability-epic flag seeded
-- alongside this one in 0023) is untouched here -- it still has no real
-- feature behind it yet.
-- =============================================================================

update public.feature_flags set is_owner_configurable = true where key = 'popularity_indicator';
